title: AJMOXU
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  BING: https://www.bing.com

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/logo.png"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/ico.ico"
